# Welcome to Jekyll!
#

# Site settings
title: "#alexandsteph"
description: |
  09 •  22 •  2018
  Brazos Hall
  Austin, TX 
owner: Alex and Steph
first_published: 2018
email: wedding@alexandsteph.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexandsteph.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/
  #email: /contact/
  #instagram:
  #spotify:
  #vimeo:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
